sudo: required
dist: trusty
language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3
- 7.4
- hhvm
matrix:
  allow_failures:
  - php: hhvm
  fast_finish: true
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: hhvm
before_script:
- composer self-update
- composer install --dev
- composer require satooshi/php-coveralls:* --dev
script:
- mkdir build
- mkdir build/coverage
- vendor/bin/phpunit
notifications:
  email:
    recipients:
    - DL-PP-PHP-SDK@paypal.com
    on_success: change
