<?php

namespace PayPal\Rest\Api;

use PayPal\Rest\Common\PayPalModel;

/**
 * Class PayoutBatch
 *
 * The batch status as generated by PayPal.
 *
 * @package PayPal\Api
 *
 * @property \PayPal\Rest\Api\PayoutBatchHeader batch_header
 * @property \PayPal\Rest\Api\PayoutItemDetails[] items
 * @property \PayPal\Rest\Api\Links[] links
 */
class PayoutBatch extends PayPalModel
{
    /**
     * A batch header that includes the generated batch status.
     *
     * @param \PayPal\Rest\Api\PayoutBatchHeader $batch_header
     * 
     * @return $this
     */
    public function setBatchHeader($batch_header)
    {
        $this->batch_header = $batch_header;
        return $this;
    }

    /**
     * A batch header that includes the generated batch status.
     *
     * @return \PayPal\Rest\Api\PayoutBatchHeader
     */
    public function getBatchHeader()
    {
        return $this->batch_header;
    }

    /**
     * Array of the items in a batch payout.
     *
     * @param \PayPal\Rest\Api\PayoutItemDetails[] $items
     * 
     * @return $this
     */
    public function setItems($items)
    {
        $this->items = $items;
        return $this;
    }

    /**
     * Array of the items in a batch payout.
     *
     * @return \PayPal\Rest\Api\PayoutItemDetails[]
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Append Items to the list.
     *
     * @param \PayPal\Rest\Api\PayoutItemDetails $payoutItemDetails
     * @return $this
     */
    public function addItem($payoutItemDetails)
    {
        if (!$this->getItems()) {
            return $this->setItems(array($payoutItemDetails));
        } else {
            return $this->setItems(
                array_merge($this->getItems(), array($payoutItemDetails))
            );
        }
    }

    /**
     * Remove Items from the list.
     *
     * @param \PayPal\Rest\Api\PayoutItemDetails $payoutItemDetails
     * @return $this
     */
    public function removeItem($payoutItemDetails)
    {
        return $this->setItems(
            array_diff($this->getItems(), array($payoutItemDetails))
        );
    }


    /**
     * Sets Links
     *
     * @param \PayPal\Rest\Api\Links[] $links
     *
     * @return $this
     */
    public function setLinks($links)
    {
        $this->links = $links;
        return $this;
    }

    /**
     * Gets Links
     *
     * @return \PayPal\Rest\Api\Links[]
     */
    public function getLinks()
    {
        return $this->links;
    }

}
